### ISSUE TITLE
macOS: Click-and-drag causes fatal crash

### ISSUE THREAD

**Issue by corfidbizna** [SolraBizna/tsong#18]
On at least macOS, clicking and dragging a song causes a fatal crash of the app. Errors are as follows: 

```
(<unknown>:49217): Gtk-WARNING **: 13:30:31.085: Cannot load drag icon from icon name text-x-generic

(<unknown>:49217): Gtk-CRITICAL **: 13:30:31.086: _cairo_surface_extents: assertion 'surface != NULL' failed
**
Gdk:ERROR:../gdk/quartz/gdkdnd-quartz.c:44:_gdk_quartz_window_drag_begin: assertion failed: (_gdk_quartz_drag_source_context == NULL)
Bail out! Gdk:ERROR:../gdk/quartz/gdkdnd-quartz.c:44:_gdk_quartz_window_drag_begin: assertion failed: (_gdk_quartz_drag_source_context == NULL)
Abort trap: 6
```

**Comment by SolraBizna** [comment]
Explicitly setting an icon removes the crash, but the operations still don't work at all on macOS.

**Comment by SolraBizna** [comment]
This was a bug in GTK+, [issue #2881](https://gitlab.gnome.org/GNOME/gtk/-/issues/2881) on their issue tracker, that was only recently fixed. Explicitly setting an icon works around the bug, but reveals that the drag and drop code is broken in some other way. I'm not able to make any further progress at this time.
