### ISSUE TITLE
Songs Don't Start From the Beginning (Rare)

### ISSUE THREAD

**Issue by corfidbizna** [SolraBizna/tsong#2]
About 3/50 songs (based on my current sample set) start 0.5-2 seconds into the song rather than the beginning. Hitting previous on these songs plays from beginning per normal, as does re-encountering the beginning of the song from the previous in the playlist. 

Behavior is rare and inconsistent, making further assessment difficult.

**Comment by SolraBizna** [comment]
Does this bug still occur in the current version?

**Comment by corfidbizna** [comment]
Issue not reproducible; will close issue unless it resurfaces.
