### ISSUE TITLE
Icons for Buttons Don't Draw

### ISSUE THREAD

**Issue by corfidbizna** [SolraBizna/tsong#6]
SVG-based icons don't render properly; some button icons on Linux get drawn sometimes, though why those icons are different is unclear and why it's not Linux-universal is also unclear.

**Comment by SolraBizna** [comment]
I've made several serious attempts to figure out what's going on, and I can't. It all works correctly on Sigma, my workstation, but not on Zephyr, my personal laptop. Both are running Debian Bullseye and are up to date. Both are using the same theme. I just don't know what's different. Even running it in `strace`, everything appears... totally the same.

I'm putting off further work on this for now.
